id: A89115679
title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
  Jamyang Khyentse Wangpo
type: translation
pechas:
- IDB7875DB
- IE4F34829
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:47:50.718018
  last_modified_at: 2023-01-04 12:47:50.718043
  collections:
  - Katok Situ Chökyi Gyatso Series
  - Works of Tibetan Masters
alignment_to_base:
  IDB7875DB/2935: 7AFE
  IE4F34829/21A8: 7AFE
